### PR TITLE
feat: add Member Contact List report (LANDA-706 / LAN-38)

### PR DESCRIPTION
**Pull request by melanieroedel**
Just like Member Address List, but for contacts
Now also with a filter on "name" (member id), not as link, but as a data field filter to allow for a flexible %str% search - a feature we may want to extend to Member Address List

### CODE REVIEW

**Comment by melanieroedel** [comment]
Please don't merge today. A release is planned with other features approved by the client

**Comment by barredterra** [comment]
@scdanieli this is ready for review now

**Review by scdanieli — APPROVED** [review]
I introduced a base class for the member contact and member address report and refactored them a bit. There is still room for improvement, but it should be sufficient for now.

I also made the filters behave the same way in both reports.

**Pull request merged**
