### PR TITLE
fix: get_current_member_data (LAN-353)

### PR DESCRIPTION
**Pull request by barredterra**
Should have been changed as part of #170

### CODE REVIEW

**Comment by marination** [comment]
@barredterra Needs changes in a few more places:
- https://github.com/alyf-de/landa/blob/d1f2fe65c968e31e78be9477f9b310c5ba521088/landa/overrides.py#L11
- https://github.com/alyf-de/landa/blob/d1f2fe65c968e31e78be9477f9b310c5ba521088/landa/water_body_management/report/members_in_water_body_management/members_in_water_body_management.py#L13

Some older patches too I think ?:
- https://github.com/alyf-de/landa/blob/d1f2fe65c968e31e78be9477f9b310c5ba521088/landa/patches/add_user_perm_on_company.py#L9-L17
- https://github.com/alyf-de/landa/blob/d1f2fe65c968e31e78be9477f9b310c5ba521088/landa/patches/link_user_to_member.py#L22-L27

**Comment by marination** [comment]
Also in:
https://github.com/alyf-de/landa/blob/21c71ebb90cebbaaa0b41531cb42392fa3467915/landa/commands/__init__.py#L35

**Comment by barredterra** [comment]
> Some older patches too I think

@marination I'm not sure about the patches... While migrating an old database the data will still be in the old places, right?

**Pull request merged**
