### PR TITLE
feat: custom markers (LAN-773)

### PR DESCRIPTION
**Pull request by barredterra**
Depends on https://github.com/alyf-de/frappe/pull/16

https://github.com/alyf-de/landa/assets/14891507/222a123f-2750-4285-b9c9-1c4aeaa0e5d3

Todo:

- [x] Rotation (try https://github.com/bbecquet/Leaflet.RotatedMarker/tree/master)
- [x] ~Add image URL to GeoJSON~ provide icon URLs via API
    This way we can change the icon without updating all the GeoJSON data.
- [x] Hide Custom Marker section for users who cannot edit the map
- [x] show correct icon while placing new marker
- [ ] show correct rotation while placing new marker
- [ ] show correct rotation while moving existing marker

### CODE REVIEW

**Comment by barredterra** [comment]
@marination this PR is ready. Could you give it a final review?

Known issues:

- The custom icon shows only after the marker is placed
- While moving a custom marker around, the custom icon temporarily loses its rotation

If you can think of a solution for these, I'd love to hear it. Otherwise, we can revisit this later.

**Comment by marination** [comment]
@barredterra 
1) Make marker the icon before click (we could re-run this snippet on rotation change maybe, so that the icon before the marker is placed is also rotated)
Essentially overwrite the controls.
```js
var Marker=  L.icon({iconUrl: "/files/5a362498d26358.3248465915134977528618.png",
	iconAnchor: new L.Point(12, 12),
	iconSize: [24, 24],
});

L.DrawToolbar.include({
    getModeHandlers: function(map) {
      return [
        {
          enabled: this.options.polyline,
          handler: new L.Draw.Polyline(map, this.options.polyline),
          title: L.drawLocal.draw.toolbar.buttons.polyline
        },
        {
          enabled: this.options.polygon,
          handler: new L.Draw.Polygon(map, this.options.polygon),
          title: L.drawLocal.draw.toolbar.buttons.polygon
        },
        {
          enabled: this.options.rectangle,
          handler: new L.Draw.Rectangle(map, this.options.rectangle),
          title: L.drawLocal.draw.toolbar.buttons.rectangle
        },
        {
          enabled: this.options.circle,
          handler: new L.Draw.Circle(map, this.options.circle),
          title: L.drawLocal.draw.toolbar.buttons.circle
        },
       {
          enabled: this.options.circlemarker,
          handler: new L.Draw.Circle(map, this.options.circlemarker),
          title: L.drawLocal.draw.toolbar.buttons.circlemarker
        },
        {
          enabled: true,
          handler: new L.Draw.Marker(cur_frm.get_field("location").map, { icon: Marker }),
          title: 'Place custom marker'
        },
      ]
    }
});
```

2) Rotate marker on drag (the "drag" event listener should call `_applyRotation`, but I can't figure it out)

**Comment by marination** [comment]
The rest LGTM

**Pull request merged**
